# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvtSampler <- function(y, mu, selected, threshold, precision, nsamp, burnin, trim, samporder, verbose) {
    .Call('_variationalReg_mvtSampler', PACKAGE = 'variationalReg', y, mu, selected, threshold, precision, nsamp, burnin, trim, samporder, verbose)
}

modmvtSampler <- function(y, mu, selected, threshold, precision, nsamp, burnin, trim, verbose, allowedNonModel) {
    .Call('_variationalReg_modmvtSampler', PACKAGE = 'variationalReg', y, mu, selected, threshold, precision, nsamp, burnin, trim, verbose, allowedNonModel)
}

